### ISSUE TITLE
"it's" changing to "its"

### ISSUE THREAD

**Issue by soheilpro** [caub/pg-tsquery#14]
Hi,

Parsing `it's` returns `its`.

Is there any way to make it return `it&s` instead?

**Comment by caub** [comment]
Hi, oh good point, I think recently we had to do this https://github.com/caub/pg-tsquery/blob/master/index.js#L220 where we replace single quotes by an empty string

We could make the replacement configurable `m.groups.word.replace(/'/g, this.singleQuoteReplacer || '')` or something

If you have a bit more time that I, maybe make a PR with quicks tests

**Comment by soheilpro** [comment]
Thanks for your quick response. I'll wait for the fix as it's not very critical.

**Comment by caub** [comment]
Ok now the option is added, you could do

```js
const tsquery = Tsquery({singleQuoteReplacement: '&'});
tsquery(`It's working`)+'' // It&s&working`
```

note that if you use `{singleQuoteReplacement: ' '` for example, the result would probably make postgresql ts_query crash

**Comment by soheilpro** [comment]
Thank you so much.
