### ISSUE TITLE
Negation should not be applied in some cases

### ISSUE THREAD

**Issue by blasterpistol** [caub/pg-tsquery#15]
An input is just some serial number.

pg-tsquery produces the same result whether there is space character in front of negation or not:
```js
parse('TS01-H-18011-005')
// TS01&!H&!18011&!005

parse('TS01 -H -18011 -005')
// TS01&!H&!18011&!005
```

Postgres has different result depending on the presence of a space character in front of negation:
```sql
select websearch_to_tsquery('TS01-H-18011-005');
--> 'ts01-h' <-> 'ts01' <-> 'h' <-> '18011' <-> '-005'

select websearch_to_tsquery('TS01 -H -18011 -005');
--> 'ts01' & !'h' & !'18011' & !'005'
```

This is useful in cases like SN inventory, slugs, and so on.

**Comment by caub** [comment]
@blasterpistol agreed

Do you know a bit github actions? I didn't manage to configure it with postgres yet https://github.com/caub/pg-tsquery/pull/16 if you can help, thanks

**Comment by caub** [comment]
Thanks for the help, I tried a fix but CI didn't work

From my googling we need to set the hostname to localhost, but I don't know how

**Comment by caub** [comment]
Ok done, thanks for the help!
