### ISSUE TITLE
Negated wildcard phrase produces invalid syntax

### ISSUE THREAD

**Issue by tommoor** [caub/pg-tsquery#20]
I was testing this module out in production and within 24h someone entered a term like this 😅 

`-"keyword"*`

…which produces the invalid syntax:

`!("keyword"):*`

…perhaps a wildcard after a phrase should just be dropped?

**Comment by caub** [comment]
Good catch, I'll try a fix when I've time

**Comment by caub** [comment]
For now it may be possible to fix this case by customizing the default regexes: https://github.com/caub/pg-tsquery/blob/master/index.js#L59-L64

**Comment by caub** [comment]
I'll check if `!("keyword":*)` is valid, in which case it's a precedence fix to do in the parser

**Comment by caub** [comment]
yes it is, ok so

**Comment by caub** [comment]
Fixed, thanks for reporting
