### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by MoltenCoffee** [caub/pg-tsquery#23]
There seems to be small issue with the documentation:

```js
const tsquery = require('pg-tsquery')(/* options can be passed to override the defaults */);

pool.query('SELECT * FROM tabby WHERE to_tsvector(col) @@ to_tsquery($1)', [tsquery(str)]);
```

Seeing as the exported `tsquery` function returns a function, I believe this should be:

```js
tsquery()(str)
```

**Comment by caub** [comment]
yea, but in the first line the function is already called once:
```js
const tsquery = require('pg-tsquery')();
```
but it's a bit confusing indeed

**Comment by MoltenCoffee** [comment]
Oops, totally missed that! Was using ESM, so basically skipped that line. Nevermind!
