### ISSUE TITLE
How to escape + and - modificators?

### ISSUE THREAD

**Issue by testarossaaaaa** [caub/pg-tsquery#5]
I have product SKU numbers like "G1-ABC", and search simply not found it with this library. The same with international phone numbers like "+37544:*" because + interpreted as modificators.

**Comment by caub** [comment]
Nice catch, I'll implement quoting, using signe or double quotes to search literal values

**Comment by DenisNeustroev** [comment]
This will be good

**Comment by caub** [comment]
I pushed a configurable version

```js
const tsquery = require(pg-tsquery')({});

console.log(tsquery('G1-ABC'));
console.log(tsquery('+a37544:*'));
/*
G1&!ABC
a37544:*
*/

const tsquery2 = require('pg-tsquery')({
    OR: /^\s*(?:[|,]|or)/i,
    AND: /^(?!\s*(?:[|,]|or))(?:[\s&:|,!]|and)*/i,
    FOLLOWED_BY: /^\s*<(?:(?:(\d+)|-)?>)?/,
    WORD: /^[\s*&<:,|]*([\s!]*)[\s*&<:,|]*([^\s,|&<:*()[\]!]+)/,
    PAR_START: /^\s*!*[([]/,
    PAR_END: /^[)\]]/,
    NEGATED: /!$/,
    PREFIX: /^(\*|:\*)*/,
    TAIL_OP: '&',
});

console.log(tsquery2('G1-ABC'));
console.log(tsquery2('+37544:*'));
/*
G1-ABC
+37544:*
*/
```

The options are still a bit complex maybe, and also I need to have tests with different configurations than the default one, feel free to participate

**Comment by testarossaaaaa** [comment]
Can we just disable some options with this approach?

**Comment by caub** [comment]
@testarossaaaaa This is what the configuration above does, I know it's a bit scary, but this config is simpler than the [default one](https://github.com/caub/pg-tsquery/blob/master/index.js#L7-L15), `+`, `-` are not parsed

An even simpler one (no `or` and `and` parsing, but make sure to test it with enough inputs, and see if it pg never throws
```js
const tsquery3 = require('pg-tsquery')({
    OR: /^\s*[|,]/,
    AND: /^(?!\s*[|,])[\s&:|,!]*/,
    FOLLOWED_BY: /^\s*<(?:(?:(\d+)|-)?>)?/,
    WORD: /^[\s*&<:,|]*([\s!]*)[\s*&<:,|]*([^\s,|&<:*()[\]!]+)/,
    PAR_START: /^\s*!*[([]/,
    PAR_END: /^[)\]]/,
    NEGATED: /!$/,
    PREFIX: /^(\*|:\*)*/,
    TAIL_OP: '&',
});

console.log(tsquery3('G1-ABC'));
console.log(tsquery3('+37544:*'));
/*
G1-ABC
+37544:*
*/
```

**Comment by caub** [comment]
@testarossaaaaa I've pushed an update, now you can use quotes: https://github.com/caub/pg-tsquery/blob/master/test/data-default.json#L105-L106

the returned string is then transformed as:
```
postgres=# select to_tsquery('Test&\"quoted<->text<->G1-ABC<->+37544<->\"');
                               to_tsquery                                
-------------------------------------------------------------------------
 'test' & 'quot' <-> 'text' <-> ( 'g1-abc' & 'g1' & 'abc' ) <-> '+37544'
```

**Comment by linojon** [comment]
Apparently now the keys are camel case and you can override just the negate rule in the constructor, eg

```
const tsParser = new Tsquery({
  negated: /!$/
})
```

**Comment by caub** [comment]
Yes correct, settings fields are camel cased now as of version 8 https://github.com/caub/pg-tsquery/commit/c68a36e9be7e6046b3d2419d32b51dcc5e19a1da
