### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by tyteen4a03** [caub/pg-tsquery#7]
It'd be great to have TypeScript definitions for this module.

**Comment by caub** [comment]
@tyteen4a03 I handled TS definitions as [jsdoc comments](https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html) for now, can you check if it works? I'm not expert in TS

**Comment by tyteen4a03** [comment]
Unfortunately it is still complaining - I think you need a separate `.d.ts` file to declare the interfaces and methods exposed.

**Comment by tyteen4a03** [comment]
The TS definitions are now there but I can no longer initialise `tsQueryParser()` without passing in an options object. 

Also, perhaps make everything in the options object optional and merge the options array with the default options at run-time?

**Comment by caub** [comment]
Ok, done
