### ISSUE TITLE
Phrase searching

### ISSUE THREAD

**Issue by tyteen4a03** [caub/pg-tsquery#8]
Right now this library doesn't seem to support searching for phrases. For example, `"sad cat"` translates to `"sad&cat"`, while Postgres's `websearch_to_tsquery` translates it to `'sad' <-> 'cat'`.

**Comment by tyteen4a03** [comment]
Just copying the output from the current docs (11): https://www.postgresql.org/docs/current/textsearch-controls.html

**Comment by caub** [comment]
Oh I missed the quotes, yea that's a great idea to do, will do

**Comment by caub** [comment]
fixed now
```
> tsquery=require('.')()
[Function]
> tsquery(`"sad cat"`)
'"sad<->cat"'
```
