### ISSUE TITLE
Regex error?

### ISSUE THREAD

**Issue by latitudehopper** [caub/pg-tsquery#9]
Hi there. I am getting this error with the default settings. Any ideas?

```
SyntaxError: Invalid regular expression: /^[\s*&+<:,|]*(?<negated>[\s!-]*)[\s*&+<:,|]*(?:(?<quote>["'])(?<phrase>.*?)\k<quote>|(?<word>[^\s,|&+<>:*()[\]!-]+))/: Invalid group
    at Object.<anonymous> (/home/ec2-user/environment/dartmoorarchive/node_modules/pg-tsquery/index.js:6:21)
    at Module._compile (module.js:653:30)
```

**Comment by caub** [comment]
@latitudehopper what is your nodejs version? try to paste that regexp in your node repl

I bet that you have node 8 or 6, that doesn't support named captures https://github.com/tc39/proposal-regexp-named-groups

We could update a little the code to avoid them, if it's really needed, they're not mandatory to use, it's just for clarity

**Comment by latitudehopper** [comment]
Ah! I bet that is it. Let me check and get back to you. Many thanks.

**Comment by latitudehopper** [comment]
That resolved it. Many thanks.

**Comment by caub** [comment]
Thanks too, added `"node": ">=10"` in package.json to make it more clear https://github.com/caub/pg-tsquery/blob/master/package.json#L6
